import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";
import { BackgroundBeamsWithCollision } from "@/components/ui/background-beams-with-collision";
import React from "react";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Scam Awareness",
	description: "Generated by Mezealot",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full">
			<body
				className={`
			${geistSans.variable} 
			${geistMono.variable} 
			antialiased

		  `}
			>
				<Header className="relative z-50" />

				<BackgroundBeamsWithCollision>{children}</BackgroundBeamsWithCollision>
			</body>
		</html>
	);
}
